name: format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: pip3 install .[dev]

    - name: Run tests
      run: |
        # pylint --rcfile=setup.cfg markov_algorithm.py tests setup.py
        isort --check-only --diff --recursive markov_algorithm.py tests setup.py
        yapf --diff --recursive markov_algorithm.onlinejudge_api tests setup.py | tee yapf.patch && test ! -s yapf.patch
        mypy markov_algorithm.py tests setup.py
